Repository fitpassTeam/fitpass, pull requests merged in 2025-06, with the labels that each got.

#44 [#43] Feature/post
  src/main/java/org/example/fitpass/common/error/ExceptionCode.java
  src/main/java/org/example/fitpass/domain/post/controller/PostController.java
  src/main/java/org/example/fitpass/domain/post/enums/PostStatus.java
  src/main/java/org/example/fitpass/domain/post/enums/PostType.java
  src/main/java/org/example/fitpass/domain/post/repository/PostRepository.java
  src/main/java/org/example/fitpass/domain/post/service/PostService.java
  src/test/java/org/example/fitpass/FitpassApplicationTests.java
Labels: fix

#48 [#47] fix : 게시물 GENERAL, NOTICE 분리
  src/main/java/org/example/fitpass/common/error/SuccessCode.java
  src/main/java/org/example/fitpass/domain/post/controller/PostController.java
  src/main/java/org/example/fitpass/domain/post/enums/PostStatus.java
  src/main/java/org/example/fitpass/domain/post/enums/PostType.java
  src/main/java/org/example/fitpass/domain/post/repository/PostRepository.java
  src/main/java/org/example/fitpass/domain/post/service/PostService.java
Labels: fix

#66 [#65] fix : RedisCacheConfig 등록
  src/main/java/org/example/fitpass/config/RedisCacheConfig.java
Labels: fix

#72 [#71] fix : 코드 리펙토링
  src/main/java/org/example/fitpass/domain/post/controller/PostController.java
  src/main/java/org/example/fitpass/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/org/example/fitpass/domain/post/dto/request/PostUpdateRequestDto.java
  src/main/java/org/example/fitpass/domain/post/dto/response/PostResponseDto.java
Labels: fix

#84 [#83] feat : reivew CRUD 생성
  src/main/java/org/example/fitpass/common/BaseEntity.java
  src/main/java/org/example/fitpass/common/error/ExceptionCode.java
  src/main/java/org/example/fitpass/common/error/SuccessCode.java
  src/main/java/org/example/fitpass/domain/review/controller/ReviewController.java
  src/main/java/org/example/fitpass/domain/review/controller/ReviewGetController.java
  src/main/java/org/example/fitpass/domain/review/dto/request/ReviewCreateRequestDto.java
  src/main/java/org/example/fitpass/domain/review/dto/request/ReviewUpdateRequestDto.java
  src/main/java/org/example/fitpass/domain/review/dto/response/GymRatingResponseDto.java
  src/main/java/org/example/fitpass/domain/review/dto/response/ReviewDetailResponseDto.java
  src/main/java/org/example/fitpass/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/org/example/fitpass/domain/review/dto/response/TrainerRatingResponseDto.java
  src/main/java/org/example/fitpass/domain/review/entity/Review.java
  src/main/java/org/example/fitpass/domain/review/repository/ReviewRepository.java
  src/main/java/org/example/fitpass/domain/review/service/ReviewService.java
Labels: feature

#86 feat : S3 연결 로직 수정
  src/main/java/org/example/fitpass/domain/fitnessGoal/entity/DailyRecord.java
  src/main/java/org/example/fitpass/domain/fitnessGoal/service/DailyRecordService.java
Labels: feature

#88 refactor:url 및 dto response 수정
  src/main/java/org/example/fitpass/common/Image/controller/ImageController.java
  src/main/java/org/example/fitpass/common/error/SuccessCode.java
  src/main/java/org/example/fitpass/domain/gym/controller/GymController.java
  src/main/java/org/example/fitpass/domain/gym/dto/response/GymResponseDto.java
  src/main/java/org/example/fitpass/domain/gym/service/GymService.java
Labels: refactor

#90 [#89] fix : 코드 리펙토링 및 S3적용
  src/main/java/org/example/fitpass/common/Image/entity/Image.java
  src/main/java/org/example/fitpass/common/dto/PageResponse.java
  src/main/java/org/example/fitpass/common/error/ExceptionCode.java
  src/main/java/org/example/fitpass/common/error/SuccessCode.java
  src/main/java/org/example/fitpass/common/jwt/JwtAuthenticationFilter.java
  src/main/java/org/example/fitpass/common/jwt/JwtTokenProvider.java
  src/main/java/org/example/fitpass/common/redis/RedisConfig.java
  src/main/java/org/example/fitpass/common/security/SecurityConfig.java
  src/main/java/org/example/fitpass/config/RedisConfig.java
  src/main/java/org/example/fitpass/config/RedisService.java
  src/main/java/org/example/fitpass/domain/gym/repository/GymRepository.java
  src/main/java/org/example/fitpass/domain/post/controller/PostController.java
  src/main/java/org/example/fitpass/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/org/example/fitpass/domain/post/dto/request/PostUpdateRequestDto.java
  src/main/java/org/example/fitpass/domain/post/dto/response/PostImageResponseDto.java
  src/main/java/org/example/fitpass/domain/post/dto/response/PostResponseDto.java
  src/main/java/org/example/fitpass/domain/post/entity/Post.java
  src/main/java/org/example/fitpass/domain/post/repository/PostRepository.java
  src/main/java/org/example/fitpass/domain/post/service/PostService.java
  src/main/java/org/example/fitpass/domain/search/controller/SearchController.java
  src/main/java/org/example/fitpass/domain/search/service/SearchService.java
  src/main/java/org/example/fitpass/domain/user/dto/LoginRequestDto.java
  src/main/java/org/example/fitpass/domain/user/service/UserService.java
  src/main/resources/application.properties
Labels: fix

#93 Refactor/gym url,dto
  src/main/java/org/example/fitpass/domain/gym/controller/GymController.java
  src/main/java/org/example/fitpass/domain/gym/dto/request/GymPhotoUpdateRequestDto.java
  src/main/java/org/example/fitpass/domain/gym/dto/request/GymRequestDto.java
  src/main/java/org/example/fitpass/domain/gym/dto/response/GymDetailResponDto.java
  src/main/java/org/example/fitpass/domain/gym/dto/response/GymResponseDto.java
  src/main/java/org/example/fitpass/domain/trainer/controller/TrainerController.java
Labels: refactor

#119 [#118] Feat/search 그라파나 프로메테우스 추가
  GRAFANA-PROMETHEUS-RDBMS/grafana/provisioning/datasources/datasource.yml
  GRAFANA-PROMETHEUS-RDBMS/prometheus/prometheus.yml
  GRAFANA-PROMETHEUS-RDBMS/query-exporter/config.yml
  docker-compose.yml
  src/main/generated/org/example/fitpass/common/QBaseEntity.java
  src/main/generated/org/example/fitpass/domain/QDummyEntity.java
  src/main/java/org/example/fitpass/config/CacheConfig.java
  src/main/java/org/example/fitpass/config/RedisConfig.java
  src/main/java/org/example/fitpass/domain/post/repository/PostRepository.java
  src/main/java/org/example/fitpass/domain/search/controller/SearchGymController.java
  src/main/java/org/example/fitpass/domain/search/controller/SearchPostController.java
  src/main/java/org/example/fitpass/domain/search/controller/SearchTrainerController.java
  src/main/java/org/example/fitpass/domain/search/entity/SearchKeywordGym.java
  src/main/java/org/example/fitpass/domain/search/entity/SearchKeywordPost.java
  src/main/java/org/example/fitpass/domain/search/entity/SearchKeywordTrainer.java
  src/main/java/org/example/fitpass/domain/search/repository/SearchGymRepository.java
  src/main/java/org/example/fitpass/domain/search/repository/SearchPostRepository.java
  src/main/java/org/example/fitpass/domain/search/repository/SearchRepository.java
  src/main/java/org/example/fitpass/domain/search/repository/SearchTrainerRepository.java
  src/main/java/org/example/fitpass/domain/search/service/SearchGymService.java
  src/main/java/org/example/fitpass/domain/search/service/SearchPostService.java
  src/main/java/org/example/fitpass/domain/search/service/SearchService.java
  src/main/java/org/example/fitpass/domain/search/service/SearchTrainerService.java
Labels: feature, refactor
